title:              INNO-SCREW
email:              robert.mura@aps.rif-ev.de
description:        Innovationszentrum für intelligentes Qualitätsmanagement in industriellen Verschraubungsvorgängen mithilfe maschineller Lernverfahren
author:             RIF e.V.
baseurl:            "/inno-screw"
url:                "https://institute-of-production-systems.github.io"

# Social Profiles
twitter_username:   
github_username:    
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
